spring:
  application:
    name: LeaderBoard
  data:
    mongodb:
      uri: mongodb+srv://vjchavan582000:P0tEaBdvfvKCkX69@quizzywhizcluster.bwsra.mongodb.net/?retryWrites=true&w=majority&appName=QuizzyWhizCluster
      database: Leaderboard
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/